apiVersion: v1
kind: Secret
metadata:
  name: stock-secret
  namespace: dev
type: Opaque
data:
  host: {{ required "Please specify db.host" .Values.db.host | b64enc }}
  database: {{ required "Please specify db.database" .Values.db.database | b64enc }}
  username: {{ required "Please specify db.username" .Values.db.username | b64enc }}
  password: {{ required "Please specify db.password" .Values.db.password | b64enc }} 
  port: {{ required "Please specify db.port" .Values.db.port | b64enc }} 
