apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: order-app
  template: 
    metadata:
      labels: 
        app: order-app
    spec: 
      containers: 
      - name: order-backend
        image: neversleeps/order-service-09:1
        ports: 
        - name: web
          containerPort: 8001
        livenessProbe:
          httpGet:
            port: 8001
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8001
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
        env: 
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: database
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: host
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: port
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: order-secret
                key: password
          - name: KAFKA_BOOTSTRAP_ADDRESS
            valueFrom:
              secretKeyRef:
                name: order-messaging-secret
                key: kafkaUrl
          - name: REDIS_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: host
          - name: REDIS_PORT
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: password